### ISSUE TITLE
Error adding integration

### ISSUE THREAD

**Issue by yeeliz** [Bepacom-Raalte/bepacom-custom_components#2]
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by Bepacom-Raalte** [comment]
Hello!

Could you perhaps give me some more information?
Can you give me:
- Add-on logs with the add-on logging level set to "INFO".
- Home Assistant logs that are relevant to the integration.
- A list of the BACnet devices connected to your network?

I assume the add-on is working fine. Is that correct?
A little tip when configuring the integration, the IP has to be 127.0.0.1 as the add-on is running locally on your Home Assistant.

**Comment by Bepacom-Raalte** [comment]
Alright, I see.

Did you install the add-on from: https://github.com/Bepacom-Raalte/bepacom-HA-Addons ?
Can you go to Settings>System>Logs and show me the full logs? If you give me the logs, it'll be a little bit more clear for me.
A 500 internal server error might suggest there is a problem with the BACnet add-on. As for this reason, I'd like the add-on logs as well. Could you give these to me? It's fine to paste it in here. I'd like as much info you can give me please.

**Comment by yeeliz** [comment]
Please check de Logs. 
Logger: aiohttp.server
Source: custom_components/bacnet_interface/config_flow.py:76
Integration: Bepacom EcoPanel BACnet/IP Interface ([documentation](https://github.com/Bepacom-Raalte/bepacom-custom_components/tree/main/custom_components/bacnet_interface))
First occurred: 11:19:12 AM (1 occurrences)
Last logged: 11:19:12 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 148, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 840, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 868, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/bacnet_interface/config_flow.py", line 76, in async_step_user
    CONF_HOST, description={"suggested_value": ip_addr}
UnboundLocalError: local variable 'ip_addr' referenced before assignment

**Comment by yeeliz** [comment]
Thanks for the update..
Yes, I have add-on installed.
Now open the window for "Write the address to the BACnet/IP add-on." but when I click on SUBMIT it gives me this error "Unknown error occurred" I tried with 127.0.0.1 and with the local network ip, and it gives me the same error. look at the log, please.
Thank you

This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/bacnet_interface/config_flow.py:92
Integration: bacnet_interface (documentation)
First occurred: 12:10:56 PM (1 occurrences)
Last logged: 12:10:56 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 271, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/bacnet_interface/config_flow.py", line 63, in async_step_user
    devicedict = await self._async_get_device(user_input[CONF_HOST])
  File "/config/custom_components/bacnet_interface/config_flow.py", line 92, in _async_get_device
    return await interface.update()
  File "/usr/local/lib/python3.10/site-packages/aioecopanel/aioecopanel.py", line 171, in update
    if not (data := await self.request("/apiv1/json")):
  File "/usr/local/lib/python3.10/site-packages/aioecopanel/aioecopanel.py", line 132, in request
    raise EcoPanelError(
aioecopanel.exceptions.EcoPanelError: (403, {'message': '<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body>\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'})

**Comment by GravySeal** [comment]
How about your add-on logs? Can you paste those?

**Comment by GravySeal** [comment]
Okay, so I can recreate this issue when the add-on hasn't detected any BACnet devices on the network. Do you see any BACnet devices in the add-on? Or do you have any on the same network as your Home Assistant connected through LAN?

**Comment by yeeliz** [comment]
I can't see any device in the add-on UI.
I do have multiple BACnet/IP devices on the same network, I can actually do "Who Is" on node-red using node-bacnet in Home Assistant and it works fine.
Any idea why I can't see these devices in add-on?

**Comment by GravySeal** [comment]
So turn off the node-red add-on and manually fill in the IP address in the BACnet add-on and restart it.  Hopefully it should work after this.

**Comment by yeeliz** [comment]
Stopping node-red now works fine.
Thank you so much.

**Comment by GravySeal** [comment]
You're welcome, glad I could help!
