### ISSUE TITLE
Unknown error when adding integration

### ISSUE THREAD

**Issue by DmitryDemin75** [Bepacom-Raalte/bepacom-custom_components#7]
I'm trying to add integration, but when setting up the address, an "unknown error" appears. I tried to use the IP address on the local network (192.168.8.239), on which the Home Assistant OS is running and 127.0.0.1 - the result is the same: "Unknown error".

When viewing network information (ha network info), this is displayed:

➜  ~ ha network info
docker:
  address: 172.30.32.0/23
  dns: 172.30.32.3
  gateway: 172.30.32.1
  interface: hassio
host_internet: true
interfaces:
- connected: true
  enabled: true
  interface: wlp2s0
  ipv4:
    address:
    - 192.168.8.239/24
    gateway: 192.168.8.1
    method: auto
    nameservers:
    - 1.1.1.1
    - 8.8.8.8
    ready: true
  ipv6:
    address:
    - fe80::149c:fbc9:889e:2a90/64
    gateway: null
    method: disabled
    nameservers: []
    ready: true
  mac: 5C:51:4F:6B:92:2F
  primary: true
  type: wireless
  vlan: null
  wifi:
    auth: wpa-psk
    mode: infrastructure
    signal: 65
    ssid: CTREND

Home Assistant CORE log:
Logger: aiohttp.server
Source: data_entry_flow.py:401
First occurred: 16:21:43 (1 occurrences)
Last logged: 16:21:43

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 177, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 298, in async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 401, in _async_handle_step
    if result.get("preview") is not None:
       ^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by Bepacom-Raalte** [comment]
Could you also provide me with the add-on logs? It might be that the add-on does not detect any devices.

**Comment by DmitryDemin75** [comment]
Where can I find these logs?
The Backnet device is definitely on the network and can be detected using third-party software
![image](https://github.com/Bepacom-Raalte/bepacom-custom_components/assets/20501380/b1b95d6e-4a48-4509-8094-6f39fa9c998b)

**Comment by DmitryDemin75** [comment]
Thank you, I apologize for the inattention! The device was detected.

**Comment by Bepacom-Raalte** [comment]
No problem! I'm glad you got it working. If you have any questions or requests, just let me know!
